Add WordPress Playground blueprint
10up/10up-sitemaps pull request #29
Opened 2024-11-11 19:35 UTC by kirtangajjar

### Description of the Change

Add WP Playground integration

Closes #25 

### How to test the Change
1. Go to https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/10up/10up-sitemaps/feature/playground-integration/.github/blueprints/blueprint.json and see that you see a working environment.

### Changelog Entry

> Added - WP Playground Integration

### Credits

Props @kirtangajjar 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [x] All new and existing tests pass.

2024-11-11 21:09 UTC, dkotter requested changes

2024-11-11 21:09 UTC, dkotter commented on .github/blueprints/blueprint.json
> +  "landingPage": "/wp-admin/plugins.php",
I think in order for this to be a proper demo, we need to do a few more things.

1. Maybe import some content
2. Generate the sitemap
3. Flush rewrites
4. Send the user to the sitemap.xml page

2025-07-07 18:35 UTC, jeffpaul commented on .github/blueprints/blueprint.json
> +  "landingPage": "/wp-admin/plugins.php",
@kirtangajjar any chance you can help make these updates to make the live demo more useful for folks?

2025-07-28 09:02 UTC, sksaju commented on .github/blueprints/blueprint.json
> +  "landingPage": "/wp-admin/plugins.php",
@dkotter @jeffpaul, I've updated this PR. Please let me know your thoughts on this. Thanks

2025-07-31 13:46 UTC, sanketio commented
@dkotter @jeffpaul I moved the `blueprint.json` file to `.wordpress.org` folder for consistency with other plugins.
I tested it on WordPress playground, and it worked fine. You can check with this link as well: https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/10up/10up-sitemaps/feature/playground-integration/.github/blueprints/blueprint.json

2025-07-31 13:46 UTC, sanketio approved these changes

2025-08-04 15:59 UTC, dkotter approved these changes

2025-08-04 15:59 UTC, merged